steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build -t us-central1-docker.pkg.dev/${PROJECT_ID}/etl-blocks/service:${SHORT_SHA} -t us-central1-docker.pkg.dev/${PROJECT_ID}/etl-blocks/service:latest .
        docker push us-central1-docker.pkg.dev/${PROJECT_ID}/etl-blocks/service:${SHORT_SHA}
        docker push us-central1-docker.pkg.dev/${PROJECT_ID}/etl-blocks/service:latest
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        REDIS_IP_PORT=$$(gcloud redis instances list --region=us-central1 --filter=name="${_REDIS_NAME_BASE}/redis-cache" --format="value(host)")
        gcloud run deploy service-etl-blocks \
        --platform=managed \
        --port=8080 \
        --set-env-vars=PG_ETL_DB=$${PG_ETL_DB},PG_ETL_HOST=$${PG_ETL_HOST},PG_ETL_USER=$${PG_ETL_USER},PG_ETL_PASS=$${PG_ETL_PASS},REDIS_IP_PORT=$${REDIS_IP_PORT} \
        --image=us-central1-docker.pkg.dev/${PROJECT_ID}/etl-blocks/service:${SHORT_SHA} \
        --allow-unauthenticated \
        --vpc-connector=redis-connector \
        --region=us-central1
    secretEnv:
      - 'PG_ETL_DB'
      - 'PG_ETL_HOST'
      - 'PG_ETL_USER'
      - 'PG_ETL_PASS'
substitutions:
  _REDIS_NAME_BASE: projects/${PROJECT_ID}/locations/us-central1/instances
availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/ETL_PostgreSQL_database/versions/1
      env: 'PG_ETL_DB'
    - versionName: projects/${PROJECT_ID}/secrets/ETL_PostgreSQL_URL/versions/1
      env: 'PG_ETL_HOST'
    - versionName: projects/${PROJECT_ID}/secrets/ETL_PostgreSQL_username/versions/1
      env: 'PG_ETL_USER'
    - versionName: projects/${PROJECT_ID}/secrets/ETL_PostgreSQL_password/versions/1
      env: 'PG_ETL_PASS'
images:
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/etl-blocks/service:${SHORT_SHA}'
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/etl-blocks/service:latest'
